#!/bin/bash

UNACCAPTABLE_JIRA_TICKET_STATUSES=(Cancelled Closed)
LAST_COMMIT_MESSAGE=$(git show -s --format=%B)
JIRA_TICKET_NUMBER=$(echo ${LAST_COMMIT_MESSAGE} | grep -Eo '[A-Z]+-[0-9]+')
JIRA_TICKET_STATUS=$(curl -s --location --request GET "${JIRA_DOMAIN}/rest/api/2/issue/${JIRA_TICKET_NUMBER}" --header 'Accept: application/json' --header 'Authorization: Basic ${JIRA_AUTH_BASIC}' | jq -r ".fields.status.name")

CAN_BE_PUSHED=$(printf "%s\n" "${UNACCAPTABLE_JIRA_TICKET_STATUSES[@]}" | grep -c "^${JIRA_TICKET_STATUS}$")
if [[ "$CAN_BE_PUSHED" -eq 1 ]]; then
  echo "=========--- Commit is stopped! ---========="
  echo ""
  echo "Please correct the ticket number in the message or Stash will refuse the push"
  echo ""
  echo "Last commit message: ${LAST_COMMIT_MESSAGE}"
  echo "      Ticket number: ${JIRA_TICKET_NUMBER}"
  echo "      Ticket status: ${JIRA_TICKET_STATUS}"
  echo ""
  echo "Run \`git commit --amend\`"

  exit 1
fi
